#ifndef SHARLIN_LIBGENERICGAME_H
#define SHARLIN_LIBGENERICGAME_H
#include "vec.h"
#include "vec.c"
#include "utilsfun.h"
#include "utilsfun.c"
#include "pcardlib.h"
#include "pcardlib.c"
#include "playerlib.h"
#include "playerlib.c"
#include "gameterminallib.h"
#include "gameterminallib.c"
#endif //SHARLIN_LIBGENERICGAME_H
